server:
  port: 8888
spring:
  cloud:
    config:
      server:
# Para repositorio REMOTO
#        git:  #direccion del repositorio remoto
#          uri: https://github.com/chrisam96/configuracion_servicios
#          default-label: main
# Para repositorio LOCAL
        native:
          search-locations:
          - file:///D:\Documents\Cursos\Spring Boot - By Antonio Martín\Leccion 66
  profiles:
    active:
    - native
   
# [[[Configuracion del SERVIDOR en archivo application]]]
# 
# > Para conexiones REMOTAS
# 
# Mediante la propiedad "spring.cloud.config.server.git"
# se establece la configuracion del repositorio, usando 2 principales
# subpropiedades:
# 
#  I. uri: Direccion del repositorio remoto
#  II.default-label: Nombre de la rama dentro del repositorio
# 
# NOTA: A partir de 2021, la rama principal deja de llamarse
# "master" y pasa a ser "main"  
# 
# > Para conexiones LOCALES
# 
# I. Los archivos de configuracion de cada microservicio se colocan dentro de un directorio 
# del servidor Cloud Config.
# 
# II. Se debe indicar que el perfil a utilizar es el native (servidor local)
#    "spring.profiles.active = native"
# 
# III. Mediante la propiedad "spring:cloud:config:server:native:search-locations:file"
# se establece la localizacion (o ruta) de los archivos en el servidor de 
# configuracion del repositorio LOCAL, 
# 
# Dependiendo el SO se sigue una regla en el campo "file" en la que
# se le deben agregar / antes de la ruta del directorio:
# 
#  - 2 / para Linux
#  - 3 / para Windows
# 
# #NOTA: Esto sustituye a "spring.cloud.config.server.git.uri"