eureka:
  instance: # Nombre de la instancia
    instance-id: instancia_B
  client:
    service-url:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: servicio-productos
server:
  port: 9035